# Generated by Django 2.1.5 on 2019-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('announcement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ContestBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('problemrank', models.IntegerField()),
                ('type', models.IntegerField()),
                ('submittime', models.IntegerField()),
                ('submitid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(default='提问', max_length=50)),
                ('problem', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=50)),
                ('huifu', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='admin', max_length=50)),
                ('oj', models.CharField(default='LPOJ', max_length=50)),
                ('title', models.CharField(default='contest', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('des', models.CharField(default='contest des', max_length=500)),
                ('note', models.CharField(default='contest note', max_length=500)),
                ('begintime', models.DateTimeField()),
                ('lasttime', models.IntegerField(default=18000)),
                ('type', models.CharField(default='ACM', max_length=50)),
                ('auth', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('problemid', models.CharField(max_length=50)),
                ('problemtitle', models.CharField(default='uname', max_length=500)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
