# Generated by Django 2.1.5 on 2019-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('statue', models.CharField(max_length=5000)),
            ],
        ),
    ]
