# Generated by Django 2.1.7 on 2019-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestboard',
            name='submittime',
            field=models.BigIntegerField(),
        ),
    ]
