# Generated by Django 2.1.7 on 2019-03-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgestatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgestatus',
            name='contestproblem',
            field=models.IntegerField(default=-1),
        ),
    ]
