# Generated by Django 2.1.7 on 2019-02-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubmittion',
        ),
    ]
