# Generated by Django 2.1.5 on 2019-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(default='admin', max_length=50)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('oj', models.CharField(default='LPOJ', max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('des', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('sinput', models.TextField()),
                ('soutput', models.TextField()),
                ('source', models.TextField()),
                ('time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('hint', models.TextField(null=True)),
                ('auth', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('problem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=5)),
                ('submission', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=0)),
                ('mle', models.IntegerField(default=0)),
                ('tle', models.IntegerField(default=0)),
                ('rte', models.IntegerField(default=0)),
                ('pe', models.IntegerField(default=0)),
                ('ce', models.IntegerField(default=0)),
                ('wa', models.IntegerField(default=0)),
                ('se', models.IntegerField(default=0)),
                ('tag', models.TextField(null=True)),
                ('score', models.IntegerField(default=1000)),
                ('auth', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
